### ISSUE TITLE
0603 resistors and 0603 capacitors have different sizes

### ISSUE THREAD

**Issue by greenscreenflicker** [KiCad/Resistors_SMD.pretty#11]
The 0603 resistors and 0603 capacitors have different sizes.

I'd propose to harmonize that. My propose is to adjust the Resistors to Capacitor footprint sizes, as capacitor footprint sizes seem to be more stable.
Comments?

I'd volunteer to do that task, when time is available.

**Comment by yaqwsx** [comment]
I would appreciate this unification. I also agree that capacitors footprint is more suitable.

**Comment by greenscreenflicker** [comment]
@michal777 @SchrodingersGat What are your opinions? If yes, I'll do that when I have some spare time.

**Comment by SchrodingersGat** [comment]
It looks like there are deviations between most / all of the ceramic caps and SMT resistor footprints. The capacitor footprints do look better, with slightly longer pads.

I have just submited a PR which adds the component outline to the fabrication layer for the ceramic caps. I think the same should be done for the SMT resistors and they should be brought into line with the cap footprints.

**Comment by evanshultz** [comment]
@SchrodingersGat Can this issue be closed? The R and C footprints have been updated since this case was opened, and not being able to go back to old libraries it's hard for me to know the issue that your PR addressed or if there are remaining improvements.

**Comment by SchrodingersGat** [comment]
@evanshultz I believe the footprint sizes are still different. This issue can also be addressed by putting data into the chip component script. (It's just that no one has volunteered to do this work :) )

**Comment by greenscreenflicker** [comment]
@evanshultz @SchrodingersGat Yes, this issue is still open. I will work on that, thanks for the reminder.

**Comment by poeschlr** [comment]
should be solved with the new footprints generated for the new repo. (All footprints generated with the same script.)
https://github.com/KiCad/kicad-footprints/pull/3

If i missed something please reopen over at the new repo. (This repo is declared legacy.)
