### ISSUE TITLE
R_0201 and others: value on Fab layer

### ISSUE THREAD

**Issue by madworm** [KiCad/Resistors_SMD.pretty#7]
(fp_text value R_0201 (at 0 1.7) (layer F.Fab)

Why is this?

The current KiCad version (BZR5572) doesn't even support this! The text object cannot be selected in openGL mode & the result of editing it via the footprint is:

"This item has an illegal layer id. Now, forced on the front silk screen layer. Please, fix it"

**Comment by michal777** [comment]
I haven't noticed any problem with F.Fab layer in BZR5562. Maybe it's a bug? How can I reproduce that?
Moving values to silkscreen was suggested by developers.

**Comment by madworm** [comment]
It is not a problem in the footprint editor, but as soon as a footprint with this "feature" is placed onto the board, it goes sour.

**Comment by michal777** [comment]
I can't see any problems on new build. Are you sure you have fresh build and use official library? Can you create new footprint with value on F.Fab with your build? What exactly should I do to get this error message?

**Comment by madworm** [comment]
I used this:

commit 0a7be9c01d12c8be2f79a27cdbd937e2b9f85bef
Author: michal777 <nnn4000@o2.pl>
Date:   Wed Mar 11 16:49:05 2015 +0100

    changed ref, val, added .3dshapes

**Comment by madworm** [comment]
I'll shoot a video...

**Comment by michal777** [comment]
I see what the problem is. Go to Design Rules -> Layers Setup and switch on the F.Fab
I think it would be good to report a bug on launchpad. It's either bug or misleading message.

**Comment by madworm** [comment]
Will do.
